### ISSUE TITLE
NullPointerException on Death

### ISSUE THREAD

**Issue by Walker-Case** [hammy3502/mc-vr-api#46]
Null pointer thrown on player death for vrapi-3.0.8-1.20.4-forge.

`java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.player.Player.m_9236_()" because "player" is null
	at net.blf02.vrapi.common.VRAPI.playerInVR(VRAPI.java:138) ~[vrapi-3.0.8-1.20.4-forge.jar!/:?] {re:classloading}
	at com.hammy275.immersivemc.common.vr.VRRumble.rumbleIfVR(VRRumble.java:20) ~[immersivemc-1.5.0-alpha2-1.20.4-forge.jar!/:?] {re:classloading}
	at com.hammy275.immersivemc.server.tracker.RangedGrabTrackerServer.tick(RangedGrabTrackerServer.java:46) ~[immersivemc-1.5.0-alpha2-1.20.4-forge.jar!/:?] {re:classloading}
	at com.hammy275.immersivemc.common.tracker.AbstractTracker.doTick(AbstractTracker.java:14) ~[immersivemc-1.5.0-alpha2-1.20.4-forge.jar!/:?] {re:classloading}
	at com.hammy275.immersivemc.server.ServerSubscriber.onServerTick(ServerSubscriber.java:23) ~[immersivemc-1.5.0-alpha2-1.20.4-forge.jar!/:?] {re:classloading}
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?] {re:mixin,re:computing_frames}
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-11.1.17-minecraftforge.jar!/:?] {re:classloading}
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-11.1.17-minecraftforge.jar!/:?] {re:classloading}
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[guava-32.1.2-jre.jar!/:?] {}
	at jdk.proxy3.$Proxy78.tick(Unknown Source) ~[?:?] {}
	at dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:75) ~[architectury-11.1.17-minecraftforge.jar!/:?] {re:mixin,re:classloading}
	at dev.architectury.event.forge.__EventHandlerImplCommon_event_ServerTickEvent.invoke(.dynamic) ~[architectury-11.1.17-minecraftforge.jar!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:58) ~[eventbus-6.2.0.jar!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:300) ~[eventbus-6.2.0.jar!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:281) ~[eventbus-6.2.0.jar!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.post(ForgeEventFactory.java:170) ~[forge-1.20.4-49.0.48-universal.jar!/:?] {re:classloading}
	at net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactory.java:755) ~[forge-1.20.4-49.0.48-universal.jar!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:864) ~[forge-1.20.4-49.0.48-client.jar!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:93) ~[forge-1.20.4-49.0.48-client.jar!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:673) ~[forge-1.20.4-49.0.48-client.jar!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:256) ~[forge-1.20.4-49.0.48-client.jar!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
`

**Comment by hammy275** [comment]
Hi!

I'm assuming you picked up on this already based on closing the issue, but in case you didn't, this is an ImmersiveMC implementation bug, currently being tracked at https://github.com/hammy275/immersive-mc/issues/393
